### PR TITLE
Make calendar timezone, locale and dark mode aware

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

- [ ] If I have added a new page to `learn/` or `community/`, I have added it to the corresponding `_sidebar.json` file.

The [new Google Calendar widget](https://workspaceupdates.googleblog.com/2024/09/update-look-and-feel-embedded-google-calendars.html) allows us to pass some locale parameters to make events easier to navigate.

### CODE REVIEW

**Review by travishathaway — APPROVED** [review]

**Comment by kathatherine** [comment]
I don't know if this is an issue with the preview or with me, but Google Calendar isn't connecting for me in the preview.

image

**Comment by jaimergp** [comment]
> I don't know if this is an issue with the preview or with me, but Google Calendar isn't connecting for me in the preview (this is in Chrome).

Does it work in the [main conda.org](https://conda.org/community/calendar)?

**Comment by kathatherine** [comment]
> > I don't know if this is an issue with the preview or with me, but Google Calendar isn't connecting for me in the preview (this is in Chrome).
> 
> Does it work in the [main conda.org](https://conda.org/community/calendar)?

Yes, it does!

**Comment by beeankha** [comment]
Seeing the same issue; the calendar is fine on the main conda.org site but in the deployment preview it's not connecting, as @kathatherine reported.

**Comment by kathatherine** [comment]
I'm seeing the same connection issue at https://conda-forge.org/community/meetings/, which I know was recently updated.

**Comment by jaimergp** [comment]
Does the [iframe URL](https://calendar.google.com/calendar/embed?height=500&wkst=1&ctz=UTC&showTitle=0&showTz=1&showPrint=0&src=ODgwNTU3MGE0ZTFjYTIzMTk4NDI5NzFkYjQzODBlZDUxOGM0OTA1NzdjMDY0NTRhZGYyMzAzNzM0NTA2ZjM5N0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t&color=%2333b679) work for you? If it doesn't, do you see any errors?

Maybe there's an error with the way the URL is being constructed dynamically in your clients. Can you right click on the errored iframe, click on "View Page Source" and report the `src` field of the `iframe` tag?

**Comment by jaimergp** [comment]
Ok I realized I can mock timezones in Chrome, and it had to do with Sunday being detected as the first day, which the previous logic identified as `8`, which made the embed error in 400, which resulted in a redirect to an error page with headers that prevent the iframe from loading. Fun stuff. Should work now I think?

**Comment by jezdez** [comment]
Woohoo!

**Comment by kathatherine** [comment]
Looks good in the preview and live for me!

**Pull request merged**
