### PR TITLE
Reuse google calendar react component

### PR DESCRIPTION
**Pull request by goanpeca**
### Description

This PR is changing the iframe google calendar by a styled react component from 
https://github.com/ericz1803/react-google-calendar

To better suit the theme.

## Before
Screenshot 2024-02-15 at 5 08 22 PM

## After
Screenshot 2024-02-15 at 5 03 16 PM

## Demo
calendar

## See

https://github.com/ericz1803/react-google-calendar/issues/68

### CODE REVIEW

**Comment by goanpeca** [comment]
Ok so it seems that we need a newer version of react, but that might not work with the current version of docusaurus (2.3.1) used in this project. Is there a reason for using 2.3.1 still, latest version is 3.1.1 it seems

**Comment by jaimergp** [comment]
@goanpeca: I think this fixed the rendering, but we still have that moment.js locale problem.

**Comment by goanpeca** [comment]
@jaimergp I fixed the code to get the API key, but locally and on netlify I now get the following error:

Error: Docusaurus server-side rendering could not render static page with path /community/calendar because of error: Cannot read properties of null (reading "registered")

I am not sure if it is related to the warnings or if it is something different from the calendar react component :-|

**Comment by goanpeca** [comment]
It is working now as expected. 

Got this reply from the docusaurus folks:

>Your lib does not support server-side rendering, so you need to tell Docusaurus to not attempt to server-render it.

>This means bypassing static html generation of that particular calendar component, and displaying some kind of loading placeholder instead, because that component can't be run inside Node.js.

>Read docs:
[docusaurus.io/docs/docusaurus-core#browseronly](https://docusaurus.io/docs/docusaurus-core#browseronly)
[docusaurus.io/docs/advanced/ssg#browseronly](https://docusaurus.io/docs/advanced/ssg#browseronly)

If you want to have a good experience without spinners and layout shifts, it's preferable to use libraries that support SSR/SSG (running in Node.js)

**Comment by jaimergp** [comment]
Awesome, I fixed one issue with the overflow-y of the events (I got a tiny scrollbar with each event item).

Unfortunately, I think the library has a bug: conda-forge events show up at 7pm, while conda-community ones show up at 6pm. Yet both happen at the same time every other Wednesday. I think one of the events is set to UTC as the base timezone, while the other is tied to a given timezone _with_ daylight savings. The iframe does show the correct times, but this React component does not...

**Comment by jaimergp** [comment]
Maybe it'd be fixed if we ever get rid of the locale warning?

**Comment by goanpeca** [comment]
>Maybe it'd be fixed if we ever get rid of the locale warning?

Maybe 🤷🏼 

Could you locally change this line inside the following file and check if affects anything locally for you (calendar correctly shows the 2 events at the same time) 

`../conda-dot-org/node_modules/@ericz1803/react-google-calendar/dist/react-google-calendar.es.js`
Line 2699
`A = SM._abbr, z = require, z("moment/locale/" + b), Eb(A);`

**Comment by jaimergp** [comment]
Nop, the warning is gone but the 6/7pm issue persists:

image

**Comment by goanpeca** [comment]
Hmmm. What time zone are you in? I changed mi computer to Berlin, Germany and now events appear as 5:00 pm both 🤔

**Comment by jaimergp** [comment]
image

🤷 This is Chrome Version 117.0.5938.149 (Official Build) (arm64)

**Comment by jezdez** [comment]
I wonder what else is needed to move this ahead?

**Comment by jaimergp** [comment]
We couldn't fix that 6pm/7pm locale issue so we are currently blocked until that gets fixed.

**Comment by jaimergp** [comment]
Superseded by https://github.com/conda/conda-dot-org/pull/221

**Pull request closed without merging**
